# Generated by Django 5.1.6 on 2025-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_disciplina_practicante'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicante',
            name='dias_entrenamiento',
            field=models.CharField(blank=True, choices=[('Lunes Miércoles y Viernes', 'Lunes, Miércoles y Viernes'), ('Miércoles/Viernes', 'Miércoles y Viernes'), ('Martes y Jueves', 'Martes y Jueves')], max_length=50, null=True, verbose_name='Días de Entrenamiento'),
        ),
        migrations.AddField(
            model_name='practicante',
            name='hora_entrenamiento',
            field=models.CharField(blank=True, choices=[('14:30', '14:30'), ('15:30', '15:30'), ('17:45', '17:45'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:30', '20:30')], max_length=5, null=True, verbose_name='Hora de Entrenamiento'),
        ),
    ]
